INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (1, "Toy Story 2", "John Lasseter", 1999, 93);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (2, "Cars 2", "John Lasseter", 2011, 120);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (3, "Monsters Inc.", "Pete Docter", 2001, 92);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (4, "Monsters University", "Dan Scanlon", 2013, 110);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (5, "Cars", "John Lasseter", 2006, 117);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (6, "Up", "Pete Docter", 2009, 101);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (7, "WALL-E", "Andrew Stanton", 2008, 104);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (8, "Finding Nemo", "Andrew Stanton", 2003, 107);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (9, "Toy Story", "John Lasseter", 1995, 81);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (10, "A Bugs Life", "John Lasseter", 1998, 95);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (11, "Toy Story 3", "Lee Unkrich", 2010, 103);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (12, "Ratatouille", "Brad Bird", 2007, 115);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (13, "Brave", "Brenda Chapman", 2012, 102);
INSERT INTO Animations(id, Title, Director, Release_Year, Length_Minutes) VALUES (14, "The Incredibles", "Brad Bird", 2004, 116);